"""The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
Let us list the factors of the first seven triangle numbers:
 1: 1 3: 1,3 6: 1,2,3,610: 1,2,5,1015: 1,3,5,1521: 1,3,7,2128: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?"""
from decorators_k import writeResult
from math import sqrt
import sys
sys.path.insert(0, "..")


def findfac(n):
    count = 0

    for i in range(2, int(sqrt(n) + 2)):

        if n%i == 0:
            count += 2
    if sqrt(n) == int(sqrt(n)):
        count -= 1

    return count


@writeResult
def solution(x=None):
    counter = 0
    sum = 0
    while findfac(sum) < x:
        sum += counter
        counter += 1
    return sum

solution(500)

## result: 76576500. Time: 8.446630954742432